# _config.yml
title: "My notebook gallery"  # 本のタイトル
author: "abay"     # 著者
logo: null                # ロゴ画像（なければnull）
only_build_toc_files: true # _toc.ymlで指定したファイルだけビルド
execute:
  execute_notebooks: "off"
