name: deploy-book

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -U jupyter-book ghp-import

      - name: Download notebooks
        run: |
          mkdir notebooks
          curl -L -o notebooks/pandas_tips_collection.ipynb https://raw.githubusercontent.com/abay-qkt/pandas-tips-collection/main/pandas_tips_collection.ipynb
          curl -L -o notebooks/matplotlib_seaborn_tips_collection.ipynb https://raw.githubusercontent.com/abay-qkt/python-visualization-tips/main/matplotlib_seaborn_tips_collection.ipynb
          curl -L -o notebooks/plotly_tips_collection.ipynb https://raw.githubusercontent.com/abay-qkt/plotly-tips-collection/main/plotly_tips_collection.ipynb
          curl -L -o notebooks/LightGBM_handbook.ipynb https://raw.githubusercontent.com/abay-qkt/lightgbm-handbook/refs/heads/main/LightGBM_handbook.ipynb

      - name: Build the book
        run: |
          jupyter-book build .

      - name: Deploy to GitHub Pages
        run: |
          ghp-import -n -p -f _build/html
